[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/api/:splat"
  status = 200
  force = true

# Uncomment and adjust the following if you want to use environment variables
#[[headers]]
#  for = "/api/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
